FROM kaldiasr/kaldi:gpu-latest

RUN DEBIAN_FRONTEND=noninteractive && \
	apt-get update && \
	apt-get install -y \
		python3 python3-dev python3-pip \
		python python-dev python-pip \
		wget unzip && \
	apt-get clean

ADD . /gentle

RUN mkdir /gentle/ext && ln -s /opt/kaldi /gentle/ext
RUN cd /gentle && python3 setup.py develop
RUN cd /gentle && ./install_models.sh

EXPOSE 8765

VOLUME /gentle/webdata

CMD cd /gentle && python3 serve.py
